app = "cyborg-academy-api"

[build]
build-target = "api"

[http_service]
internal_port = 3000
force_https = true

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/"
